### ISSUE TITLE
Question on elaboration of pairs

### ISSUE THREAD

**Issue by atennapel** [AndrasKovacs/setoidtt#2]
I see that in your core language you give abstractions a type, this seems necessary because during elaboration we may have the situation:
`\x. b : (x : A) -> B`, which without explicit parameter types would elaborate to `\x. b` which may mean that we cannot re-typecheck the core language as we would have to guess the type of `x`.
Currently though the following happens:
`\x. b : (x : A) -> B` elaborates to `\(x : A). b` and now we can re-typecheck the core expression.

For pairs on the other hand the type is not preserved in the core language.
`(x, y) : (x : A) ** B` will elaborate to `(x, y)`, and we can no longer know the dependent sigma type. So we may not be able to typecheck the core expression anymore after elaboration.

Is this correct? Is it an issue? How would you handle this in an industrial-strength proof assistant?

In my own language the core syntax for pairs is as follows: `(x, y) : (x : A) ** B`, they always require a type annotation, this however really increases the size of the core expressions.

**Comment by AndrasKovacs** [comment]
The reason I type-annotated all binders is not re-checking, but the following: metavariables are typed, and during unification fresh metas are sometimes created, which requires the types of bound vars in scope. Also, since my implementation of unification is not type-directed, I can only get types of bound vars from annotations (and not from e.g. function types). 

For re-checking, you indeed need some annotation on pairs. Concretely, if you want to re-check bidirectionally, without using unification or metavariables, you need annotations on all bindings, plus the second projection type on pairs. The first projection type is inferable and can be omitted.

In industrial-strength solution, storing the second projection type is probably not expensive, because unification need not touch it, and inferred annotations should be relatively small if we adequately preserve sharing.

**Comment by atennapel** [comment]
Alright, thanks. With storing the second projection type do you mean that the core syntax for pairs would be something like `(a, b : x. B)`. For example for type `(t : Type) ** t` you would have `(Nat, 1 : t. t)`.

**Comment by AndrasKovacs** [comment]
Yes.
